// <auto-generated />
using ECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerce.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerce.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intel core i9",
                            Price = 430.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ryzen 9",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ryzen 7",
                            Price = 330.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Intel core i5",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Intel core i7",
                            Price = 320.00m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nvidia 1080",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = 7,
                            Name = "AMD Radeon 8940",
                            Price = 198.00m
                        },
                        new
                        {
                            Id = 8,
                            Name = "MSI GTX 1660",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dell ATI",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Nvidia Quadro GT-100",
                            Price = 650.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
